import{i as l,S as d}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();function f(t){const s="43748337-b5dbfef6f8220f61277bc8c0d",r=`https://pixabay.com/api/?${new URLSearchParams({key:s,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(r).then(e=>{if(!e.ok)throw new Error("There are no images matching your search query. Please try again!");return e.json()}).catch(e=>{console.error("Error",e)})}function p(t){const s=document.querySelector("#gallery"),n=t.map(r=>y(r));s.insertAdjacentHTML("beforeend",n.join(""))}function y(t){return`
    <a href="${t.largeImageURL}" class="image-card">
      <img src="${t.webformatURL}" alt="${t.tags}">
      <div class="details">
        <p>Likes: ${t.likes}</p>
        <p>Views: ${t.views}</p>
        <p>Comments: ${t.comments}</p>
        <p>Downloads: ${t.downloads}</p>
      </div>
    </a>
  `}const u=document.querySelector("#search-form"),a=document.querySelector("#search-input"),c=u.querySelector('button[type="submit"]'),m=document.querySelector("#gallery");a.addEventListener("input",()=>{a.value.trim()===""?c.disabled=!0:c.disabled=!1});u.addEventListener("submit",t=>{t.preventDefault(),m.innerHTML="";const s=a.value.trim(),n=document.getElementById("loader");n.style.display="block",f(s).then(r=>{r.total===0?l.error({message:"No images found for your search query. Please try again.",position:"topRight"}):(p(r.hits),h())}).catch(r=>{console.error("Error fetching data:",r),l.error({message:"Failed to fetch data. Please try again later.",position:"topRight"})}).finally(()=>{a.value="",c.disabled=!0,n.style.display="none"})});function h(){new d("#gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
